"""Run locally: python scripts/generate_status.py

Runs the actual test suite and mechanical checks, and generates a
small, timestamped status snippet -- so the README's test count is a
GENERATED FACT, not a hand-typed number. This project has had to
correct a manually-typed test count (going stale after new tests were
added) more than once; this script exists so that stops being possible
for the test count specifically, even though the surrounding prose
still has to be written by hand.

This does NOT edit README.md automatically -- it prints the snippet
for a human to paste in, deliberately. Auto-editing prose risks
silently overwriting a carefully-worded surrounding paragraph; a
generated, copy-pasteable fact is the safer middle ground.
"""
from __future__ import annotations

import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def run_pytest_summary() -> str:
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "tests/", "-q"],
        cwd=REPO_ROOT, capture_output=True, text=True,
    )
    match = re.search(r"(\d+) passed", result.stdout)
    if not match:
        return f"UNKNOWN (pytest did not report a clean pass count -- exit code {result.returncode})"
    n_passed = match.group(1)
    failed_match = re.search(r"(\d+) failed", result.stdout)
    if failed_match:
        return f"{n_passed} passed, {failed_match.group(1)} FAILED -- do not treat as a clean status"
    return f"{n_passed} passed"


def run_mechanical_checks() -> str:
    result = subprocess.run(
        [sys.executable, "scripts/run_all_checks.py"], cwd=REPO_ROOT, capture_output=True, text=True,
    )
    return "PASSED" if result.returncode == 0 else "FAILED -- see scripts/run_all_checks.py output"


def main():
    print("Running pytest (this may take a minute or two)...")
    test_summary = run_pytest_summary()
    print("Running mechanical checks (stale claims, orphaned test bodies)...")
    checks_summary = run_mechanical_checks()

    snippet = (
        f"<!-- Generated by scripts/generate_status.py -- paste into README.md, "
        f"do not hand-type this line -->\n"
        f"**Status snapshot ({datetime.now(timezone.utc).isoformat()}): "
        f"tests: {test_summary}. Mechanical checks: {checks_summary}.**"
    )
    print("\n" + "=" * 78)
    print("GENERATED STATUS SNIPPET -- copy the line below into README.md by hand:")
    print("=" * 78)
    print(snippet)
    print("=" * 78)


if __name__ == "__main__":
    main()
